// A controlled list (rather than free text) so member locations stay
// consistent and can be reliably filtered/matched later.
export const TOWN_OPTIONS: string[] = [
  "Colombo", "Dehiwala", "Moratuwa", "Sri Jayawardenepura Kotte", "Kaduwela",
  "Negombo", "Gampaha", "Ja-Ela", "Wattala", "Kelaniya", "Kadawatha", "Nittambuwa",
  "Kandy", "Peradeniya", "Katugastota", "Gampola", "Nawalapitiya", "Wattegama",
  "Matale", "Dambulla", "Galewela",
  "Nuwara Eliya", "Hatton", "Talawakele", "Ginigathhena",
  "Galle", "Ambalangoda", "Hikkaduwa", "Elpitiya", "Bentota",
  "Matara", "Weligama", "Akuressa", "Deniyaya",
  "Hambantota", "Tangalle", "Tissamaharama", "Ambalantota",
  "Jaffna", "Chavakachcheri", "Point Pedro", "Nallur",
  "Kilinochchi", "Mullaitivu", "Vavuniya",
  "Mannar",
  "Trincomalee", "Kinniya", "Kantale",
  "Batticaloa", "Kattankudy", "Eravur",
  "Ampara", "Kalmunai", "Akkaraipattu",
  "Kurunegala", "Kuliyapitiya", "Narammala", "Pannala", "Mawathagama",
  "Puttalam", "Chilaw", "Wennappuwa", "Anamaduwa",
  "Anuradhapura", "Kekirawa", "Medawachchiya",
  "Polonnaruwa", "Kaduruwela", "Hingurakgoda",
  "Badulla", "Bandarawela", "Haputale", "Welimada", "Mahiyanganaya",
  "Monaragala", "Wellawaya", "Bibile",
  "Ratnapura", "Balangoda", "Embilipitiya", "Pelmadulla",
  "Kegalle", "Mawanella", "Warakapola", "Rambukkana",
  "Homagama", "Maharagama", "Kesbewa", "Piliyandala", "Kottawa",
  "Panadura", "Kalutara", "Beruwala", "Horana", "Wadduwa",
  "Avissawella", "Hanwella", "Kolonnawa",
];
